version: '3'

services:
  app:
    container_name: cbamecapacita
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HUGGINGFACE_TOKEN=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
      - DB_USER=usuario1
      - DB_PASSWORD=usuario1
      - DB_HOST=5.161.118.67
      - DB_PORT=3306
      - DB_NAME=CBAMECAPACITA
    ports:
      - 8502:8501
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge