services:
  app:
    container_name: cbamecapacita
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HUGGINGFACE_TOKEN=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
      - DB_USER=usuario1
      - DB_PASSWORD=usuario1
      - DB_HOST=5.161.118.67
      - DB_PORT=3306
      - DB_NAME=CBAMECAPACITA
    ports:
      - 8502:8501
    restart: unless-stopped
    networks:
      front-net:
        ipv4_address: 172.21.0.3

networks:
  front-net:                #Gateway: 172.21.0.1
    external: true