name: Portainer Webhook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Activar Webhook de Portainer
        run: |
          curl -X POST https://5.161.118.67:9443/api/stacks/webhooks/88952271-b4af-4a95-83a1-2da9be119942 -k