[supabase]
url = "https://gonsfiizpyknwhjufqea.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbnNmaWl6cHlrbndoanVmcWVhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjU0NzM1NiwiZXhwIjoyMDQ4MTIzMzU2fQ.Mwz3gQeI-oGGjBwm3uwdNPvtQMqppTOWs_Dwx54XQPY"

[HuggingFace]
huggingface_token = "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"

[db_credentials]
connection_string = "postgresql://usuario:contraseña@host:puerto/nombre_base_datos"