[supabase]
url = "https://gonsfiizpyknwhjufqea.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbnNmaWl6cHlrbndoanVmcWVhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjU0NzM1NiwiZXhwIjoyMDQ4MTIzMzU2fQ.Mwz3gQeI-oGGjBwm3uwdNPvtQMqppTOWs_Dwx54XQPY"

[db_credentials]
DB_USER = "usuario1"
DB_PASSWORD = "usuario1"
DB_HOST = "5.161.118.67"
DB_PORT = "3306"
DB_NAME = "CBAMECAPACITA"

[HuggingFace]
huggingface_token = "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"